# Задание 3

## 0.Формулировка

1.   **Считайте датасет из файла train.csv (это данные о выживаемости на Титанике)**
2.   **Выведите основную информацию о датасете: информацию о типах данных, число пропусков, средние значения и т.д.**
3. **Посчитайте процент выживаемости у каждого класса пассажиров (Pclass)**
4. **Выведите самое популярное мужское и самое популярное женское имя на корабле**
5. **Выведите самое популярное мужское и самое популярное женское имя на корабле в каждом классе**
6. **Выведите часть таблицы с пассажирами, возраст которых больше 44 лет**
7. **Выведите часть таблицы с пассажирами, возраст которых меньше 44 лет и которые мужского пола**
**8. Выведите количества n-местных кабин (в которых было 2, 3, 4, ... человека)**

## 1.Считывание датасета из файла

In [1]:
#pip install numpy
import numpy as np
#pip install pandas
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

## 2.Основная информация о датасете

In [3]:
# Информация о типах данных
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
# Информация об индексах внутри датафрейма
df.index

RangeIndex(start=0, stop=891, step=1)

In [5]:
#  Набор статистических данных
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
# Число пропусков в таблице
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
# Подсчет элементов с одинаковыми значениями в том или ином столбце
df['Age'].value_counts()

Age
24.00    30
22.00    27
18.00    26
28.00    25
30.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

## 3.Процент выживаемости у каждого класса пассажиров

In [8]:
# Число пассажиров в каждом классе
df_count=df['Pclass'].value_counts()
df_count

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [9]:
# Число выживших в каждом классе
df_surv=df.groupby("Pclass")["Survived"].sum()
df_surv

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

In [10]:
#Процент выживаемости у каждого класса пассажиров
df_surv_rate=df_surv/df_count*100
df_surv_rate

Pclass
1    62.962963
2    47.282609
3    24.236253
dtype: float64

In [11]:
pd.DataFrame({'Pclass': [1, 2, 3], 'Count': [df_count[1], df_count[2], df_count[3]],'Survived': [df_surv[1], df_surv[2], df_surv[3]], 'Survival rate,%':[df_surv_rate[1], df_surv_rate[2], df_surv_rate[3]]})

   Pclass  Count  Survived  Survival rate,%
0       1    216       136        62.962963
1       2    184        87        47.282609
2       3    491       119        24.236253

## 4.Cамое популярное мужское и самое популярное женское имя на корабле

In [12]:
# Как прописано мужское имя
df.loc[df['Sex']=='male','Name']

0             Braund, Mr. Owen Harris
4            Allen, Mr. William Henry
5                    Moran, Mr. James
6             McCarthy, Mr. Timothy J
7      Palsson, Master. Gosta Leonard
                    ...
883     Banfield, Mr. Frederick James
884            Sutehall, Mr. Henry Jr
886             Montvila, Rev. Juozas
889             Behr, Mr. Karl Howell
890               Dooley, Mr. Patrick
Name: Name, Length: 577, dtype: object

In [13]:
# Как прописано женское имя
df.loc[df['Sex']=='female','Name']

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
8      Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                    Nasser, Mrs. Nicholas (Adele Achem)
                             ...
880         Shelley, Mrs. William (Imanita Parrish Hall)
882                         Dahlberg, Miss. Gerda Ulrika
885                 Rice, Mrs. William (Margaret Norton)
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
Name: Name, Length: 314, dtype: object

In [14]:
# Функция для выдедения мужского имени из строки
def parse_first_name_male(name):
    first = name.str.extract(r"Mr\.\s+[^(]*\((\w+)", expand=False)
    first.loc[first.isna()] = name.str.extract(r"\.\s+(\w+)", expand=False)
    return first

# Функция для выдедения женского имени
def parse_first_name_female(name):
    first = name.str.extract(r"Mrs\.\s+[^(]*\((\w+)", expand=False)
    first.loc[first.isna()] = name.str.extract(r"\.\s+(\w+)", expand=False)
    return first

In [15]:
# Выделенные мужских имен
male_names = parse_first_name_male(df.loc[df['Sex']=='male','Name'])
male_names

0           Owen
4        William
5          James
6        Timothy
7          Gosta
         ...
883    Frederick
884        Henry
886       Juozas
889         Karl
890      Patrick
Name: Name, Length: 577, dtype: object

In [16]:
# Популярность мужского имени
male_names.value_counts()

Name
William    35
John       25
George     14
Thomas     13
Charles    13
           ..
Frans       1
Nedelio     1
Kristo      1
Johann      1
Juozas      1
Name: count, Length: 285, dtype: int64

In [17]:
# Выделенные женские имена
female_names = parse_first_name_female(df.loc[df['Sex']=='female','Name'])
female_names

1       Florence
2          Laina
3           Lily
8      Elisabeth
9          Adele
         ...
880      Imanita
882        Gerda
885     Margaret
887     Margaret
888    Catherine
Name: Name, Length: 314, dtype: object

In [18]:
# Популярность женского имени
female_names.value_counts()

Name
Anna         15
Mary         14
Elizabeth    11
Margaret     10
Alice         7
             ..
Asuncion      1
Sallie        1
Hannah        1
Imanita       1
Gerda         1
Name: count, Length: 177, dtype: int64

## 5.Cамое популярное мужское и самое популярное женское имя на корабле в каждом классе

In [19]:
#Часть базы с пассажирами мужского пола
df_male=df[df['Sex'] == 'male']
df_male = df_male.rename(columns={'Name': 'Ful_Name'})

In [20]:
#Объединение таблицы с данными пасссажиров мужского пола и таблицей выделенных имен
df_male_names = pd.concat([df_male, male_names], sort=False, axis=1)
df_male_names

,PassengerId,Survived,Pclass,Ful_Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Owen
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,William
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,James
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Timothy
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,Gosta
...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,Frederick
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,Henry
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Juozas
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Karl
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Patrick

In [21]:
# Популярность мужского имени по классам
df_res5_1 = df_male_names.groupby(["Pclass"])["Name"].value_counts()
df_res5_1

Pclass  Name
1       William     11
        John         9
        George       6
        Arthur       5
        Charles      5
                    ..
3       Wazli        1
        Wilhelm      1
        Yoto         1
        Youssef      1
        Yousseff     1
Name: count, Length: 346, dtype: int64

In [22]:
#Часть базы с пассажирами женского пола
df_female=df[df['Sex'] == 'female']
df_female = df_female.rename(columns={'Name': 'Ful_Name'})

In [23]:
#Объединение таблицы с данными пасссажиров женского пола и таблицей выделенных имен
df_female_names = pd.concat([df_female, female_names], sort=False, axis=1)
df_female_names

,PassengerId,Survived,Pclass,Ful_Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Florence
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Lily
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Elisabeth
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Adele
...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,Imanita
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S,Gerda
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,Margaret
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Margaret
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Catherine

In [24]:
# Популярность женского имени по классам
df_res5_2 = df_female_names.groupby(["Pclass"])["Name"].value_counts()
df_res5_2

Pclass  Name
1       Elizabeth    5
        Margaret     5
        Alice        4
        Mary         4
        Anna         3
                    ..
3       Thamine      1
        Torborg      1
        Velin        1
        Virginia     1
        Wendla       1
Name: count, Length: 223, dtype: int64

## 6.Часть таблицы с пассажирами, возраст которых больше 44 лет

In [25]:
df[df['Age'] > 44]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

## 7.Часть таблицы с пассажирами, возраст которых меньше 44 лет и которые мужского пола

In [26]:
#Часть таблицы с пассажирами мужского пола
df_male=df[df['Sex'] == 'male']
df_male

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [27]:
#Часть таблицы с пассажирами мужского пола, возраст которых меньше 44 лет
df_male[df_male['Age'] < 44]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050,NaN,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,NaN,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.050,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.275,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.500,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.050,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q

## 8.Количества *n* - местных кабин (в которых было 2, 3, 4, ... человека)

In [28]:
# Подсчет элементов с одинаковыми значениями в том или ином столбце
df['Cabin'].value_counts()

Cabin
G6             4
C23 C25 C27    4
B96 B98        4
F2             3
D              3
              ..
E17            1
A24            1
C50            1
B42            1
C148           1
Name: count, Length: 147, dtype: int64

In [29]:
# Количество человек в каждой кабине согласно базе данных
df_cabin=df.groupby("Cabin")["Cabin"].value_counts()
df_cabin_people = df_cabin.to_frame(name='Capacity')
df_cabin_people

       Capacity
Cabin
A10           1
A14           1
A16           1
A19           1
A20           1
...         ...
F33           3
F38           1
F4            2
G6            4
T             1

[147 rows x 1 columns]

In [30]:
#Количества n-местных кабин
df_cabin_people.groupby(["Capacity"])["Capacity"].value_counts()

Capacity
1    101
2     38
3      5
4      3
Name: count, dtype: int64